### ISSUE TITLE
"If you are going to use this program, please drop me a line." But how and where?

### ISSUE THREAD

**Issue by gdoron** [hebcal/hebcal-js#72]
Do you have an email address I can explain to what I'm doing with the library and ask for the permission to use it in a closed source program?

Thanks,
Doron

**Comment by mkopinsky** [comment]
The author's email address can be found on his website: http://danny.sadinoff.com/

**Comment by gdoron** [comment]
That's the original author, I already got his permission.
I think(?) I already need the permission of the node.js port author.

**Comment by Scimonster** [comment]
The "please drop me a line" is really just because i'm curious to know how people are actually using the library. You could make an issue here, and my email and Twitter links are in my profile.

About using it in closed source, i'm not entirely sure how it would work. Since Hebcal was originally under the GPL, when i ported it to NodeJS, i kept it GPL. In theory i might be able to release a version under the MIT license, except that parts of the code were kept from the original Hebcal, which makes that problematic, i think. I'm not a lawyer and find the GPL's infectious nature confusing.

**Comment by mkopinsky** [comment]
According to [this SE post](https://opensource.stackexchange.com/questions/6699/if-i-translate-port-a-repository-from-one-programming-language-to-another-do-i), the port is still GPL. Or at least the portions that you directly ported are.

You wouldn't be able to release the library as a whole as MIT, but you're welcome to grant others (individuals or wholesale) permission to use it. Which, combined with permission from the original author, would allow someone to use it in closed source software.

**Comment by Scimonster** [comment]
[Assuming this has legal validity], I grant permission in general to use the original portions of the HebcalJS port in a closed-source program under the MIT license, on condition that similar permission is obtained from @dsadinoff and @mjradwin regarding their portions of the original code.

**Comment by gdoron** [comment]
@Scimonster I'm building a calendar for a famous Israeli news website.

Example of how it looks at the moment:

![image](https://user-images.githubusercontent.com/6141009/65311552-3b20df00-db99-11e9-91ae-4da1d8620570.png)

(You can see some bugs there that were fixed in #67 but weren't released on NPM yet)

Great stuff, and thanks for your help!
